### ISSUE TITLE
[Task] Add a guide on how to contribute to cryostat project

### ISSUE THREAD

**Issue by tthvo** [rhat-openjdk-interns/operator-knowledge-hub#10]
Currently, we have a description in intern manual but it would be nice to add in pictures. 

We can reuse this guide: https://gist.github.com/tthvo/88707d0877841164114684177e899a4d

**Comment by tthvo** [comment]
Maybe this should be more suited on a separate repo. Or if you want we can rename this repo to something like `cryostat-knowledge-hub`, then a sub-dir for operator, general, cryostat, cryostat-web, etc.

What do you think @maxcao13?

**Comment by maxcao13** [comment]
> Maybe this should be more suited on a separate repo. Or if you want we can rename this repo to something like `cryostat-knowledge-hub`, then a sub-dir for operator, general, cryostat, cryostat-web, etc.
> 
> What do you think @maxcao13?

I am wondering how much of the content should be different from the info that is already on each `cryostat` repository. I'm not sure what is the use case of using this, rather than updating the docs of each `cryostat.io` repo. Is this more of a step-by-step troubleshooting type of knowledge hub?

**Comment by tthvo** [comment]
Yehh truee! And probably a bit more details of what each step (i.e. command) does? I think it would be too much contents if they are specified in `cryostat.io`.

**Comment by maxcao13** [comment]
Makes sense, then yea I think renaming it to a more general name would be nice and then subfolders would just be the names of each repository.

**Comment by tthvo** [comment]
This should be done in a separate repo since moving to new organization.

**Comment by tthvo** [comment]
Related to https://github.com/rhat-openjdk-interns/cryostat-knowledge-hub/issues/9.

Will be closed after PR for that issue.
