### ISSUE TITLE
[Task] Guide should mention operator managed by OLM appears on console

### ISSUE THREAD

**Issue by tthvo** [rhat-openjdk-interns/operator-knowledge-hub#13]
See original comments: 
https://github.com/cryostatio/cryostat-operator/pull/432#issuecomment-1197253148
https://github.com/cryostatio/cryostat-operator/pull/432#issuecomment-1197283723

@maxcao13 u wanna write a section for it?

**Comment by maxcao13** [comment]
Sure, no problem.
