### ISSUE TITLE
[Task] Knowledge hub should be general and add a sub-dir for cryostat-operator

### ISSUE THREAD

**Issue by tthvo** [rhat-openjdk-interns/operator-knowledge-hub#14]
See issue: https://github.com/rhat-openjdk-interns/cryostat-knowledge-hub/issues/2
Duplicate of #5

**Comment by maxcao13** [comment]
I think for now, its okay to leave it as it is since we are only working on cryostat-operator anyways, but in the future if there happens to be other operators to develop then it would make sense. Maybe just keep this issue in the backlog until then? Very lazy initialization :-D

**Comment by tthvo** [comment]
Haha make sense :D Later if there is an chore work, I would just do a quick reorganizing then just as a ground work.

**Comment by tthvo** [comment]
Closing because it is a duplicate of #5.
